before_script:
  - ./scripts/prepare_build.sh
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install

rspec:
  script: bundle exec rspec spec

rubocop:
  script: bundle exec rubocop
